### ISSUE TITLE
Bug with the GUI on Linux

### ISSUE THREAD

**Issue by benoit9126** [smarie/env-switcher-gui#12]
@smarie: Here is the small experiment you expected about your GUI tool on my Linux

```console
benoit@mirabelle:~/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5$ ls
envswitch      imageformats  libpython3.5m.so.1.0  libQt5Widgets.so.5  LICENSE       platforms  VERSION__
envswitch_gui  lib           libQt5Core.so.5       libyaml-0.so.2      LICENSE-PyQt  README.md
envswitch.ico  libffi.so.6   libQt5Gui.so.5        libz.so.1           LICENSE-Qt    resources
benoit@mirabelle:~/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5$ ./envswitch_gui &
[1] 6220
benoit@mirabelle:~/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5$ *** ENVSWITCH <1.3.0> ***
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

Reinstalling the application may fix this problem.

[1]+  Abandon                 (core dumped) ./envswitch_gui
benoit@mirabelle:~/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5$ ./envswitch --help
Usage: envswitch [OPTIONS] COMMAND [ARGS]...

  Envswitch commandline. Use 'envswitch COMMAND --help' to get help on any
  specific command below.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  apply
  list
  open
benoit@mirabelle:~/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5$ rm libQt5*.so*
rm : supprimer fichier 'libQt5Core.so.5' ? y
rm : supprimer fichier 'libQt5Gui.so.5' ? y
rm : supprimer fichier 'libQt5Widgets.so.5' ? y
benoit@mirabelle:~/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5$ ./envswitch_gui 
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/travis/miniconda/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "envswitch/gui.py", line 19, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.6' not found (required by /home/benoit/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5/lib/python3.5/PyQt5/QtCore.so)
benoit@mirabelle:~/Téléchargements/envswitch-1.3.0-linux-x86_64-3.5$ ls
envswitch      envswitch.ico  lib          libpython3.5m.so.1.0  libz.so.1  LICENSE-PyQt  platforms  resources
envswitch_gui  imageformats   libffi.so.6  libyaml-0.so.2        LICENSE    LICENSE-Qt    README.md  VERSION__
```

The command line interface seems to work fine but the GUI tool does not work with your Qt shared library. It does not work also with the Qt of my system (from the official Ubuntu repository) because of a version problem.

**Comment by smarie** [comment]
Great report, thanks Benoît !
Ok so that's better than I thought. It seems that libQt5XcbQpa.so.5 lib is missing in the resulting folder (from [this discussion](https://stackoverflow.com/a/18532522/7262247)). What is strange is that on my linux mint 32bit VM I dont need it... 
 
Could you please try to extract the following file [libQt5XcbQpa.so.5.tar.gz](https://github.com/smarie/env-switcher-gui/files/1401432/libQt5XcbQpa.so.5.tar.gz) in the envswitch root folder and try again to execute `./envswitch_gui &` ? It should fix the problem of displaying the GUI.

Thanks again!

**Comment by benoit9126** [comment]
On your Linux mint, an installed version of Qt (system-wide) can have replaced the missing local library file.

I have added the library but it still does not work:
```console
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ls
envswitch      imageformats  libpython3.5m.so.1.0  libQt5Widgets.so.5        libyaml-0.so.2  LICENSE-PyQt  README.md
envswitch_gui  lib           libQt5Core.so.5       libQt5XcbQpa.so.5         libz.so.1       LICENSE-Qt    resources
envswitch.ico  libffi.so.6   libQt5Gui.so.5        libQt5XcbQpa.so.5.tar.gz  LICENSE         platforms     VERSION__
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ./envswitch_gui 
*** ENVSWITCH <1.4.0> ***
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Abandon (core dumped)
```

NB: I did this test with envswitch 1.4.0

**Comment by benoit9126** [comment]
The output of the `ldd` command can also help:
```console
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ldd libQt5XcbQpa.so.5
./libQt5XcbQpa.so.5: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: version `Qt_5' not found (required by ./libQt5XcbQpa.so.5)
	linux-vdso.so.1 =>  (0x00007fff04134000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f1110316000)
	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007f1110112000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f110ff0a000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f110fcf0000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f110fae6000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f110f8c4000)
	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007f110f6bf000)
	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007f110f4ba000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f110f2b3000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f110f0ab000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f110eea7000)
	libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007f110ec99000)
	libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007f110ea95000)
	libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007f110e892000)
	libxcb-xinerama.so.0 => not found
	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007f110e677000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f1110564000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f110e366000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f110e02c000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f110dde9000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f110db3f000)
	libQt5Gui.so.5 (0x00007f110d5f3000)
	libQt5Core.so.5 (0x00007f110d060000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f110ce43000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f110cac1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f110c7b8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f110c3ee000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f110c1e9000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f110bfe5000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f110bddf000)
	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007f110bbd9000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f110b98d000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f110b71d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f110b519000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f110b2f0000)
	libz.so.1 (0x00007f110b0d9000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x./libQt5XcbQpa.so.5: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: version `Qt_5' not found (required by ./libQt5XcbQpa.so.5)
	linux-vdso.so.1 =>  (0x00007fff04134000)00007f110aeb4000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f110ac42000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f110aa2c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f110a824000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1110518000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f110a79f000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f110a59c000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f110a399000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f110a196000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f1109f67000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f1109d55000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f1109b52000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f110994c000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f1109733000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f110952e000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f1109328000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f1109117000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f1108ef5000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f1108cd3000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f11089f2000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f11087de000)
```
The first 3-4 lines are very interesting. It seems that there are still some version problems.

**Comment by smarie** [comment]
Your error message (as well as when I do `ldd libqxcb.so`) shows that libQt5DBus.so.5 was also missing. My mistake, it was also mentioned in the stack overflow [thread](https://stackoverflow.com/a/18532522/7262247). Could you copy it from [libQt5DBus.so.5.tar.gz](https://github.com/smarie/env-switcher-gui/files/1401844/libQt5DBus.so.5.tar.gz) into envswitch root folder too ? It should do the trick.

Note: for reference, the qt library used and shipped inside envswitch is [this version](https://github.com/smarie/PyQt5-minimal/releases/download/0.2.0/Qt5.6.3_lgpl_minimal-Linux-x86_64.tar.gz).

**Comment by smarie** [comment]
Note that if this still does not work, my last chance could be to modify the [PyQt5-minimal project](https://github.com/smarie/PyQt5-minimal) so that on linux platforms Qt is built with `-qt-xcb` option, as explained [here](http://doc.qt.io/qt-5/linux-requirements.html). However I would rather first try without such an extreme option :)

**Comment by benoit9126** [comment]
It seems that you need to use the complicated version...

```console
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ls
envswitch      libpython3.5m.so.1.0    libQt5XcbQpa.so.5         LICENSE-Qt
envswitch_gui  libQt5Core.so.5         libQt5XcbQpa.so.5.tar.gz  platforms
envswitch.ico  libQt5DBus.so.5         libyaml-0.so.2            README.md
imageformats   libQt5DBus.so.5.tar.gz  libz.so.1                 resources
lib            libQt5Gui.so.5          LICENSE                   VERSION__
libffi.so.6    libQt5Widgets.so.5      LICENSE-PyQt
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ./envswitch_gui 
*** ENVSWITCH <1.4.0> ***
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Abandon (core dumped)
```

**Comment by benoit9126** [comment]
NB: if I delete all the libQt shared library, it nearly works:
```console
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ rm libQt5*
rm : supprimer fichier 'libQt5Core.so.5' ? y
rm : supprimer fichier 'libQt5DBus.so.5' ? y
rm : supprimer fichier 'libQt5DBus.so.5.tar.gz' ? y
rm : supprimer fichier 'libQt5Gui.so.5' ? y
rm : supprimer fichier 'libQt5Widgets.so.5' ? y
rm : supprimer fichier 'libQt5XcbQpa.so.5' ? y
rm : supprimer fichier 'libQt5XcbQpa.so.5.tar.gz' ? y
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ls
envswitch      lib                   libz.so.1     platforms
envswitch_gui  libffi.so.6           LICENSE       README.md
envswitch.ico  libpython3.5m.so.1.0  LICENSE-PyQt  resources
imageformats   libyaml-0.so.2        LICENSE-Qt    VERSION__
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ./envswitch_gui 
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/travis/miniconda/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "envswitch/gui.py", line 21, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.6' not found (required by /home/benoit/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5/lib/python3.5/PyQt5/QtCore.so)
```

In fact, the installed version of Qt5 from the Ubuntu 16.04LTS repository is Qt5.5.1
```console
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ dpkg -l libqt5core*
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom            Version      Architecture Description
+++-==============-============-============-=================================
un  libqt5core5    <aucune>     <aucune>     (aucune description n'est disponi
ii  libqt5core5a:a 5.5.1+dfsg-1 amd64        Qt 5 core module
``` 
Do you really use a feature of Qt5.6 which is not in Qt5.5.1?

**Comment by smarie** [comment]
No, I want the app to be completely 'standalone' on both windows and linux targets.
If you put back all the libQt5* in the root folder, what is the output of `ldd ./platforms/libqxcb.so` now ? and `ldd libQt5XcbQpa.so.5` ? Maybe there is a remaining import issue. Otherwise I'll go for the recompilation using `-qt-xcb`. And I will try to get access to a linux x64 machine next week so that I dont bother you until I've solved this.
Thanks again for the help!

**Comment by benoit9126** [comment]
Here are the output of the two commands you propose:
```console
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ldd ./platforms/libqxcb.so
	linux-vdso.so.1 =>  (0x00007ffc25da0000)
	libQt5XcbQpa.so.5 (0x00007fdb22fd3000)
	libQt5Gui.so.5 (0x00007fdb22989000)
	libQt5Core.so.5 (0x00007fdb223f6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdb22074000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdb21caa000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fdb21aa8000)
	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007fdb218a4000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fdb2169c000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fdb21482000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fdb21278000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fdb21056000)
	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007fdb20e51000)
	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007fdb20c4c000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fdb20a45000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007fdb2083d000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fdb20639000)
	libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007fdb2042b000)
	libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007fdb20227000)
	libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007fdb20024000)
	libxcb-xinerama.so.0 => not found
	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007fdb1fe09000)
	libQt5DBus.so.5 (0x00007fdb22f19000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fdb1faf8000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fdb1f7be000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fdb1f57b000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fdb1f2d1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdb1f0b4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdb1edab000)
	libz.so.1 (0x00007fdb1eb94000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fdb1e922000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fdb1e6fd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdb1e4e7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdb1e2e3000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdb1e0db000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdb22ed5000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fdb1ded6000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fdb1dcd2000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fdb1dacc000)
	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007fdb1d8c6000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fdb1d656000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fdb1d42d000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fdb1d22a000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fdb1d027000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fdb1ce24000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fdb1cbf5000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fdb1c9e3000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fdb1c7e0000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fdb1c5da000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fdb1c3c1000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fdb1c1bc000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fdb1bfb6000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fdb1bda5000)
```

and 
```console
benoit@mirabelle:~/Téléchargements/envswitch-1.4.0-linux-x86_64-3.5$ ldd libQt5XcbQpa.so.5
	linux-vdso.so.1 =>  (0x00007fffe69e4000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f5fa9933000)
	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007f5fa972f000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f5fa9527000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f5fa930d000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f5fa9103000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f5fa8ee1000)
	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007f5fa8cdc000)
	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007f5fa8ad7000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f5fa88d0000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f5fa86c8000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f5fa84c4000)
	libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007f5fa82b6000)
	libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007f5fa80b2000)
	libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007f5fa7eaf000)
	libxcb-xinerama.so.0 => not found
	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007f5fa7c94000)
	libQt5DBus.so.5 (0x00007f5fa9b7e000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f5fa7983000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f5fa7649000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f5fa7406000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f5fa715c000)
	libQt5Gui.so.5 (0x00007f5fa6c10000)
	libQt5Core.so.5 (0x00007f5fa667d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5fa6460000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5fa60de000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5fa5dd5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5fa5a0b000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f5fa5806000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f5fa5602000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f5fa53fc000)
	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007f5fa51f6000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f5fa4f86000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5fa4d82000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f5fa4b59000)
	libz.so.1 (0x00007f5fa4942000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f5fa471d000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f5fa44ab000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5fa4295000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5fa408d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5fa9b35000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f5fa3e8a000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f5fa3c87000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f5fa3a84000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f5fa3855000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f5fa3643000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f5fa3440000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f5fa323a000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f5fa3021000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f5fa2e1c000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f5fa2c16000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f5fa2a05000)
```

**Comment by smarie** [comment]
libxcb-xinerama not found. According to this thread https://forum.qt.io/topic/75701/qt-static-compile-linux-error-loading-libxcb-xinerama-so/7 the proposed option (compile qt with -qt-xcb) seems the same so I'll give it a try. I will tell you when it's ready

**Comment by smarie** [comment]
We will close the issue when the resulting app will have been tested :)

**Comment by smarie** [comment]
Benoît, the latest release is [here](https://github.com/smarie/env-switcher-gui/releases/download/1.4.1/envswitch-1.4.1-linux-x86_64-3.5.tar.gz). Let me know if that solves the issue. On my side I will check if the 32 bit version is affected by the change.
